### PR TITLE
Add Godot4.x support

### PR DESCRIPTION
**Pull request by anosatsuk124**
I've implemented a `Godot 4.x` support for this program.

### CODE REVIEW

**Comment by tbillington** [comment]
Hey! thank you for this @anosatsuk124 

I have used Godot a little recently, and I know that there are some things stored in .godot that are not exactly just build artifacts, such as `export_credentials.cfg` and `extension_list.cfg`. I don't know if there may be more so I might do some research to see if there are any others before I merge Godot support :)

**Comment by anosatsuk124** [comment]
I've overlooked the files that are not build artifacts 😨. I always delete them without cares. Thanks for your information! I'll check some files, and will commit additionally if possible!

**Comment by tbillington** [comment]
I checked in the godot engine chat, seems like it's actually fine and common to nuke the whole `.godot` directory.

https://chat.godotengine.org/channel/general

**Comment by tbillington** [comment]
Thank you for your contribution :)

**Pull request merged**
