### PR TITLE
add support for pycache and jupyter-notebook checkpoints

### PR DESCRIPTION
**Pull request by Stunkymonkey**

### CODE REVIEW

**Comment by tbillington** [comment]
don't worry about the lint, I can fix that :)

**Comment by Stunkymonkey** [comment]
anything else i am missing out?

**Comment by Stunkymonkey** [comment]
@tbillington all checks are passing. Any comments?

**Comment by tbillington** [comment]
Thank you for your PR 🎉 ! , apologies it took me a while to get to :)

**Pull request merged**
